export const STOP_SUBSCRIPTION = "STOP_SUBSCRIPTION";

export const NODES_LOADING = 'NODES_LOADING'
export const NODES_LOADED = 'NODES_LOADED'

export const EDGES_LOADING = 'EDGES_LOADING'
export const EDGES_LOADED = 'EDGES_LOADED'

export const CONFIG_LOADING = 'CONFIG_LOADING'
export const CONFIG_LOADED = 'CONFIG_LOADED'
