import { Edges } from '../collections.js'
import { Meteor } from 'meteor/meteor'

import { ValidatedMethod } from 'meteor/mdg:validated-method'
import { SimpleSchema } from 'meteor/aldeed:simple-schema'

const EDGE_ID_ONLY = new SimpleSchema({
  edgeId: Edges.simpleSchema().schema('_id'),
}).validator({ clean: true, filter: false })


/**
* Create a single edge
*
* @instance {ValidatedMethod}
* @param {Object} node the raw node data (generated by `MakeEdge()`)
* @return {Object} the Node object as inserted in Mongo
*/
export const edgeCreate = new ValidatedMethod({
  name: 'edge.create',
  validate: Edges.simpleSchema()
    .pick([
      'topogramId',
      'data.id',
      'data.name',
      'data.color',
      'data.group',
      'data.notes',
      'data.lat',
      'data.lng',
      'data.start',
      'data.end',
      'data.starred',
      'data.weight',
      'data.source',
      'data.target',
    ]).validator(),
  run(edge) {
    return Edges.insert( edge )
  }
})

/**
* Delete a single edge
*
* @instance {ValidatedMethod}
* @param {String} edgeId _id of the edge to delete
* @return {Object} the Node object as removed from Mongo
*/
export const edgeDelete = new ValidatedMethod({
  name: 'edge.delete',
  validate: EDGE_ID_ONLY,
  run({ edgeId }) {
    return Edges.remove( edgeId )
  }
})


/**
* Create multiple edges at once
*
* @instance {ValidatedMethod}
* @param {Array} edges an array of edge data
* @return {Object} the edges as inserted in Mongo
*/

const edgeSchema = Edges.schema.pick([
  'data.id',
  'data.name',
  'data.color',
  'data.group',
  'data.notes',
  'data.lat',
  'data.lng',
  'data.start',
  'data.end',
  'data.starred',
  'data.weight',
  'data.source',
  'data.target'
])

export const edgeCreateMany = new ValidatedMethod({
  name: 'edge.createMany',
  validate: new SimpleSchema({
    'topogramId': { type: String },
    'edges' : { type : [ edgeSchema ], minCount: 1 }
  }).validator(),
  run({ topogramId, edges }) {
    const ok = edges.map( e =>  ({ ...e, topogramId }) )
    return Edges.batchInsert( ok )
  }
})

/**
* Update edge properties
*
* @instance {ValidatedMethod}
* @param {String} nodeId _id of the node to be updated
* @param {Object} data the new data to be updated
* @return {Object} the updated Edge object as returned by Mongo
*/


const edgeUpdateSchema = Edges.schema.pick([
  'data.name',
  'data.color',
  'data.group',
  'data.notes',
  'data.lat',
  'data.lng',
  'data.start',
  'data.end',
  'data.starred',
  'data.weight'
])


export const edgeUpdate = new ValidatedMethod({
  name: 'edge.update',
  validate: new SimpleSchema([
    edgeUpdateSchema,
    { 'edgeId': {
      type: String
    }
    },
    {
      'data.source': {
        type: String,
        label: 'The source of the edge',
        optional :true
      }
    },
    {
      'data.target': {
        type: String,
        label: 'The target of the edge',
        optional :true
      }
    }
  ]).validator(), // TODO :check if ID exists,
  run( { edgeId, data }) {
    const $set = {}
    Object.keys(data).map( d=> $set['data.'+d] = data[d])
    return Edges.update({ 'data.id': edgeId }, { $set })
  }
})

/**
* Delete multiple edges
*
* @instance {ValidatedMethod}
* @param {Array} edgesId list of edge _ids deleted
* @return {Object} the Node object as inserted in Mongo
*/

export const edgeDeleteMany = new ValidatedMethod({
  name: 'edge.deleteMany',
  validate: new SimpleSchema({
    edgeIds: { type: [String], minCount: 1 }
  }).validator(), // TODO :check if ID exists,
  run({ edgeIds }) {
    return Edges.remove( { '_id' : { $in : edgeIds } } )
  }
})

/**
* Delete all edges in a Topogram
*
* @instance {ValidatedMethod}
* @param {String} topogramId the _id of the topogram
* @return {Object} the Edges object as inserted in Mongo
*/
export const edgeDeleteAll = new ValidatedMethod({
  name: 'edge.deleteAll',
  validate: new SimpleSchema({ 'topogramId': { type: String } }).validator(),
  // TODO :check if ID exists
  run( topogramId ) {
    return Edges.remove(topogramId)
  }
})

Meteor.methods( {

  batchInsertEdges( edges ) {
    // console.log(edges.length)
    return Edges.batchInsert( edges )
  },

  deleteEdge( edgeId ) {
    const edge = Edges.findOne( {
      'data.id': edgeId
    } )
    Edges.remove( edge )
  },

  deleteEdgesByTopogramId( topogramId ) {
    return Edges.remove( {
      topogramId
    } )
  }
} )
